image:
  file: .gitpod.Dockerfile

tasks:
  - command: platformio run -e d1_mini

vscode:
  extensions:
    - ms-vscode.cpptools@1.1.2
    - platformio.platformio-ide@2.2.1
    - eamodio.gitlens@11.0.6
    - 2gua.rainbow-brackets@0.0.6
